name: RCDTest
favicon: null
layout_spectrum: 0.9053023371379822
typography_spectrum: 0.4073651130311191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.012814091285690665
  lightness: 0.046803783159703016
  saturation: 0.1563301756978035
  rhythmicContrast: 0.5634292468894273
purpose: []
